apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-config
  namespace: argo-cd
spec:
  project: cluster-addons
  syncPolicy:
    automated: {}
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: cluster-addons
  source:
    path: config/argo-workflows-config/
    repoURL: https://github.com/sandile-yakka/argo-cluster-addons
    targetRevision: master